import { MiniAppItem } from '@/types/miniapp';

export const SYSTEM_MINI_APPS: MiniAppItem[] = [
  {
    id: 'planner',
    name: 'Day Planner',
    nameVi: 'Kế hoạch ngày',
    description: 'Smart daily schedule, hourly timeboxing, and task prioritization matrix.',
    descriptionVi: 'Lập lịch trình thông minh theo giờ, timeboxing và ma trận việc cần làm trong ngày.',
    icon: '🗓️',
    iconName: 'calendar-clock',
    category: 'productivity',
    color: '#6366f1',
    gradient: 'from-indigo-500 to-sky-500',
    badge: 'Phổ biến',
    badgeVariant: 'primary',
    isSystem: true,
    featured: true,
    tags: ['timeboxing', 'schedule', 'focus', 'agenda'],
    author: 'Apexa Core',
    version: '2.4.0',
    rating: 4.9,
  },
  {
    id: 'whiteboard',
    name: 'Whiteboard',
    nameVi: 'Bảng vẽ tương tác',
    description: 'Infinite collaborative canvas for mindmaps, flowcharts, sticky notes, and system architecture.',
    descriptionVi: 'Bảng vẽ vô hạn cộng tác thời gian thực: vẽ sơ đồ tư duy, flowchart quy trình, sticky note.',
    icon: '🎨',
    iconName: 'palette',
    category: 'collaboration',
    color: '#8b5cf6',
    gradient: 'from-purple-500 to-pink-500',
    badge: 'Mới',
    badgeVariant: 'purple',
    isSystem: true,
    featured: true,
    tags: ['canvas', 'mindmap', 'flowchart', 'brainstorm'],
    author: 'Apexa Core',
    version: '2.1.0',
    rating: 4.95,
  },
  {
    id: 'base',
    name: 'Apexa Base',
    nameVi: 'Cơ sở dữ liệu Base',
    description: 'No-code relational database with Grid, Kanban, Gallery, Form, Gantt, and Dashboard views.',
    descriptionVi: 'Cơ sở dữ liệu quan hệ không mã (Bitable) với 6 chế độ xem: Grid, Kanban, Gallery, Form, Gantt.',
    icon: '📊',
    iconName: 'database',
    category: 'productivity',
    color: '#0284c7',
    gradient: 'from-sky-500 to-blue-600',
    badge: 'Mạnh mẽ',
    badgeVariant: 'info',
    isSystem: true,
    featured: true,
    tags: ['database', 'bitable', 'spreadsheet', 'views'],
    author: 'Apexa Core',
    version: '3.0.0',
    rating: 4.92,
  },
  {
    id: 'crm',
    name: 'CRM Workspace',
    nameVi: 'Quản trị Khách hàng (CRM)',
    description: 'Customer relations, lead pipelines, deal tracking, quotations, and activity timelines.',
    descriptionVi: 'Quản lý phễu bán hàng, cơ hội giao dịch, danh bạ khách hàng doanh nghiệp và báo giá.',
    icon: '💼',
    iconName: 'briefcase',
    category: 'business',
    color: '#059669',
    gradient: 'from-emerald-500 to-teal-600',
    badge: 'Doanh nghiệp',
    badgeVariant: 'success',
    isSystem: true,
    featured: true,
    tags: ['crm', 'deals', 'customers', 'sales'],
    author: 'Apexa Core',
    version: '2.0.0',
    rating: 4.88,
  },
  {
    id: 'erp',
    name: 'ERP Hub',
    nameVi: 'Quản trị Nguồn lực (ERP)',
    description: 'Inventory warehouse management, stock in/out vouchers, sales orders, suppliers, and HR.',
    descriptionVi: 'Quản lý kho hàng, phiếu nhập/xuất kho, đơn hàng xuất khẩu/bán lẻ, nhà cung cấp và nhân sự.',
    icon: '📦',
    iconName: 'boxes',
    category: 'business',
    color: '#d97706',
    gradient: 'from-amber-500 to-orange-600',
    badge: 'Vận hành',
    badgeVariant: 'warning',
    isSystem: true,
    featured: false,
    tags: ['erp', 'inventory', 'warehouse', 'orders', 'hr'],
    author: 'Apexa Core',
    version: '1.8.0',
    rating: 4.85,
  },
  {
    id: 'pomodoro',
    name: 'Pomodoro Timer',
    nameVi: 'Đồng hồ Pomodoro',
    description: 'Deep work focus timer with custom session lengths, ambient sound alerts, and streak tracking.',
    descriptionVi: 'Đồng hồ tập trung sâu theo chu kỳ Pomodoro, âm thanh chuông sinh động, đếm phiên liên tục.',
    icon: '⏱️',
    iconName: 'timer',
    category: 'utilities',
    color: '#ef4444',
    gradient: 'from-red-500 to-rose-600',
    badge: 'Tập trung',
    badgeVariant: 'primary',
    isSystem: true,
    featured: false,
    tags: ['focus', 'timer', 'productivity', 'deepwork'],
    author: 'Apexa Core',
    version: '1.2.0',
    rating: 4.9,
  },
  {
    id: 'notes',
    name: 'Quick Scratchpad',
    nameVi: 'Ghi chú nhanh',
    description: 'Instant scratchpad with Markdown formatting, auto-save, and 1-click export to Apexa Docs.',
    descriptionVi: 'Ghi chú nháp tức thời, định dạng Markdown trực quan, tự lưu offline và chuyển đổi sang Apexa Doc.',
    icon: '📝',
    iconName: 'sticky-note',
    category: 'utilities',
    color: '#f59e0b',
    gradient: 'from-amber-400 to-yellow-500',
    badge: 'Tiện ích',
    badgeVariant: 'info',
    isSystem: true,
    featured: false,
    tags: ['notes', 'scratchpad', 'markdown', 'draft'],
    author: 'Apexa Core',
    version: '1.1.0',
    rating: 4.87,
  },
  {
    id: 'converter',
    name: 'Finance & Calculator',
    nameVi: 'Quy đổi & Tiện ích tính',
    description: 'Live currency exchange calculator (VND, USD, EUR, JPY), VAT tax estimator, and profit margin formulas.',
    descriptionVi: 'Tính toán tài chính nhanh: quy đổi ngoại tệ, tính thuế VAT 8%/10%, biên lợi nhuận và chiết khấu.',
    icon: '🧮',
    iconName: 'calculator',
    category: 'utilities',
    color: '#10b981',
    gradient: 'from-emerald-500 to-cyan-500',
    badge: 'Tiện ích',
    badgeVariant: 'success',
    isSystem: true,
    featured: false,
    tags: ['currency', 'vat', 'calculator', 'rates', 'finance'],
    author: 'Apexa Core',
    version: '1.0.0',
    rating: 4.82,
  },
];

export const DEFAULT_PINNED_APP_IDS: string[] = ['planner', 'whiteboard', 'base', 'crm'];

export function getSystemMiniApp(id: string): MiniAppItem | undefined {
  return SYSTEM_MINI_APPS.find((app) => app.id === id);
}

export const MINI_APP_CATEGORIES = [
  { id: 'all', labelVi: 'Tất cả', labelEn: 'All Apps', emoji: '✨' },
  { id: 'productivity', labelVi: 'Năng suất', labelEn: 'Productivity', emoji: '⚡' },
  { id: 'business', labelVi: 'Kinh doanh & Vận hành', labelEn: 'Business & Ops', emoji: '💼' },
  { id: 'collaboration', labelVi: 'Sáng tạo & Cộng tác', labelEn: 'Creative & Team', emoji: '🎨' },
  { id: 'utilities', labelVi: 'Tiện ích', labelEn: 'Utilities', emoji: '🛠️' },
  { id: 'custom', labelVi: 'Ứng dụng nhúng Web', labelEn: 'Web Embeds', emoji: '🌐' },
] as const;
