import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <Script
          id="ignore-extension-errors"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const ignoreError = (event) => {
                  try {
                    const filename = event.filename;
                    const error = event.error;
                    const message = event.message;
                    
                    const isExtensionError = 
                      (typeof filename === 'string' && filename.includes('chrome-extension://')) ||
                      (error && error.stack && typeof error.stack === 'string' && error.stack.includes('chrome-extension://')) ||
                      (typeof message === 'string' && (message.includes('chrome-extension://') || message.includes('Cannot redefine property: ethereum')));
                    
                    if (isExtensionError) {
                      event.stopImmediatePropagation();
                      event.preventDefault();
                    }
                  } catch (e) {}
                };

                const ignoreRejection = (event) => {
                  try {
                    const reason = event.reason;
                    
                    const isExtensionError = 
                      (reason && reason.stack && typeof reason.stack === 'string' && reason.stack.includes('chrome-extension://')) ||
                      (reason && reason.message && typeof reason.message === 'string' && (reason.message.includes('chrome-extension://') || reason.message.includes('Cannot redefine property: ethereum')));

                    if (isExtensionError) {
                      event.stopImmediatePropagation();
                      event.preventDefault();
                    }
                  } catch (e) {}
                };

                window.addEventListener('error', ignoreError, true);
                window.addEventListener('unhandledrejection', ignoreRejection, true);
              })();
            `
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
