alter table public.documents
  add column if not exists is_favorite boolean not null default false;

create index if not exists idx_documents_workspace_space_active
  on public.documents (workspace_id, space_id, is_archived, updated_at desc);
create index if not exists idx_documents_owner
  on public.documents (user_id);

create table if not exists public.document_versions (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.documents(id) on delete cascade,
  title text not null,
  icon text,
  cover_url text,
  content jsonb not null default '{"type":"doc","content":[]}'::jsonb,
  change_summary text not null default 'Autosaved revision',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_document_versions_document_created
  on public.document_versions (document_id, created_at desc);

alter table public.document_versions enable row level security;

create or replace function private.has_document_role(
  target_document_id uuid,
  allowed_roles text[]
)
returns boolean
language sql
stable
security definer
set search_path = ''
set row_security = off
as $$
  select exists (
    select 1
    from public.document_collaborators dc
    where dc.document_id = target_document_id
      and dc.user_id = (select auth.uid())
      and dc.role = any(allowed_roles)
  );
$$;

create or replace function private.can_view_document(target_document_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
set row_security = off
as $$
  select exists (
    select 1
    from public.documents d
    where d.id = target_document_id
      and (
        d.is_published
        or d.user_id = (select auth.uid())
        or private.is_workspace_member(d.workspace_id)
        or private.has_document_role(d.id, array['owner','editor','commenter','viewer'])
      )
  );
$$;

create or replace function private.can_edit_document(target_document_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
set row_security = off
as $$
  select exists (
    select 1
    from public.documents d
    where d.id = target_document_id
      and (
        d.user_id = (select auth.uid())
        or private.is_workspace_member(d.workspace_id)
        or private.has_document_role(d.id, array['owner','editor'])
      )
  );
$$;

create or replace function private.can_comment_document(target_document_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
set row_security = off
as $$
  select exists (
    select 1
    from public.documents d
    where d.id = target_document_id
      and (
        d.user_id = (select auth.uid())
        or private.is_workspace_member(d.workspace_id)
        or private.has_document_role(d.id, array['owner','editor','commenter'])
      )
  );
$$;

revoke all on function private.has_document_role(uuid, text[]) from public, anon;
revoke all on function private.can_view_document(uuid) from public;
revoke all on function private.can_edit_document(uuid) from public, anon;
revoke all on function private.can_comment_document(uuid) from public, anon;
grant execute on function private.has_document_role(uuid, text[]) to authenticated, service_role;
grant execute on function private.can_view_document(uuid) to anon, authenticated, service_role;
grant execute on function private.can_edit_document(uuid) to authenticated, service_role;
grant execute on function private.can_comment_document(uuid) to authenticated, service_role;

drop policy if exists "Users can read documents in their workspace or if shared" on public.documents;
drop policy if exists "Users can insert documents in their workspace" on public.documents;
drop policy if exists "Users can update documents in their workspace or if editors/owners" on public.documents;
drop policy if exists "Users can delete documents they own or if they are owner collaborators" on public.documents;

create policy documents_select_access on public.documents for select
to anon, authenticated using (private.can_view_document(id));
create policy documents_insert_workspace_member on public.documents for insert
to authenticated with check (user_id = (select auth.uid()) and private.is_workspace_member(workspace_id));
create policy documents_update_editor on public.documents for update
to authenticated using (private.can_edit_document(id)) with check (private.can_edit_document(id));
create policy documents_delete_manager on public.documents for delete
to authenticated using (
  user_id = (select auth.uid())
  or private.is_workspace_member(workspace_id)
  or private.has_document_role(id, array['owner'])
);

drop policy if exists "Users can read collaborator list if they have access to document" on public.document_collaborators;
drop policy if exists "Owners and editors can modify collaborators" on public.document_collaborators;

create policy document_collaborators_select_access on public.document_collaborators for select
to authenticated using (private.can_view_document(document_id));
create policy document_collaborators_insert_manager on public.document_collaborators for insert
to authenticated with check (
  exists (select 1 from public.documents d where d.id = document_id and (
    d.user_id = (select auth.uid()) or private.is_workspace_member(d.workspace_id)
    or private.has_document_role(d.id, array['owner'])
  ))
);
create policy document_collaborators_update_manager on public.document_collaborators for update
to authenticated using (
  exists (select 1 from public.documents d where d.id = document_id and (
    d.user_id = (select auth.uid()) or private.is_workspace_member(d.workspace_id)
    or private.has_document_role(d.id, array['owner'])
  ))
) with check (
  exists (select 1 from public.documents d where d.id = document_id and (
    d.user_id = (select auth.uid()) or private.is_workspace_member(d.workspace_id)
    or private.has_document_role(d.id, array['owner'])
  ))
);
create policy document_collaborators_delete_manager on public.document_collaborators for delete
to authenticated using (
  exists (select 1 from public.documents d where d.id = document_id and (
    d.user_id = (select auth.uid()) or private.is_workspace_member(d.workspace_id)
    or private.has_document_role(d.id, array['owner'])
  ))
);

drop policy if exists "Users can read comments if they can read the document" on public.document_comments;
drop policy if exists "Users can insert comments if they can comment on the document" on public.document_comments;
drop policy if exists "Users can modify their own comments" on public.document_comments;
drop policy if exists "Users can delete their own comments" on public.document_comments;

create policy document_comments_select_access on public.document_comments for select
to authenticated using (private.can_view_document(document_id));
create policy document_comments_insert_commenter on public.document_comments for insert
to authenticated with check (user_id = (select auth.uid()) and private.can_comment_document(document_id));
create policy document_comments_update_author_or_editor on public.document_comments for update
to authenticated using (user_id = (select auth.uid()) or private.can_edit_document(document_id))
with check (user_id = (select auth.uid()) or private.can_edit_document(document_id));
create policy document_comments_delete_author_or_editor on public.document_comments for delete
to authenticated using (user_id = (select auth.uid()) or private.can_edit_document(document_id));

drop policy if exists document_versions_select_access on public.document_versions;
create policy document_versions_select_access on public.document_versions for select
to authenticated using (private.can_view_document(document_id));

create or replace function private.capture_document_version()
returns trigger
language plpgsql
security definer
set search_path = ''
set row_security = off
as $$
begin
  if (
    old.title is distinct from new.title
    or old.icon is distinct from new.icon
    or old.cover_url is distinct from new.cover_url
    or old.content is distinct from new.content
  ) and not exists (
    select 1 from public.document_versions dv
    where dv.document_id = old.id
      and dv.created_by is not distinct from (select auth.uid())
      and dv.created_at > now() - interval '5 minutes'
  ) then
    insert into public.document_versions (
      document_id, title, icon, cover_url, content, change_summary, created_by
    ) values (
      old.id, old.title, old.icon, old.cover_url,
      coalesce(old.content, '{"type":"doc","content":[]}'::jsonb),
      'Autosaved revision', (select auth.uid())
    );
  end if;

  new.updated_at := now();
  return new;
end;
$$;

revoke all on function private.capture_document_version() from public, anon, authenticated;
drop trigger if exists documents_capture_version on public.documents;
create trigger documents_capture_version before update on public.documents
for each row execute function private.capture_document_version();

revoke all on table public.document_versions from anon;
grant select on table public.document_versions to authenticated;
grant usage, select on sequence public.document_versions_id_seq to authenticated;
grant select on table public.documents to anon;
grant select, insert, update, delete on table public.documents to authenticated;
grant select, insert, update, delete on table public.document_collaborators to authenticated;
grant select, insert, update, delete on table public.document_comments to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'document_versions'
  ) then
    alter publication supabase_realtime add table public.document_versions;
  end if;
end
$$;
