create schema if not exists private;

create table if not exists public.teams (
  id text primary key,
  workspace_id text,
  name text not null,
  description text not null default '',
  icon text not null default 'Users',
  department_id text,
  leader_id text,
  announcement text,
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.teams add column if not exists workspace_id text;
alter table public.teams add column if not exists description text not null default '';
alter table public.teams add column if not exists icon text not null default 'Users';
alter table public.teams add column if not exists department_id text;
alter table public.teams add column if not exists leader_id text;
alter table public.teams add column if not exists announcement text;
alter table public.teams add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.teams add column if not exists created_at timestamptz not null default now();
alter table public.teams add column if not exists updated_at timestamptz not null default now();

create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  team_id text not null,
  member_id text,
  role text not null default 'member' check (role in ('lead', 'member')),
  added_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.team_members add column if not exists member_id text;
alter table public.team_members add column if not exists role text not null default 'member';
alter table public.team_members add column if not exists added_by uuid references auth.users(id) on delete set null;
alter table public.team_members add column if not exists created_at timestamptz not null default now();

create unique index if not exists teams_workspace_name_unique
  on public.teams (workspace_id, lower(name)) where workspace_id is not null;
create index if not exists teams_workspace_idx on public.teams (workspace_id, created_at desc);
create unique index if not exists team_members_team_member_unique
  on public.team_members (team_id, member_id) where member_id is not null;
create index if not exists team_members_member_idx on public.team_members (member_id, team_id);

create or replace function private.can_view_team_workspace(target_workspace_id text)
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select exists (
    select 1
    from public.members m
    where m.user_id = (select auth.uid())
      and target_workspace_id = any(coalesce(m.workspace_ids, array[]::text[]))
  ) or exists (
    select 1
    from public.workspaces w
    where w.id = target_workspace_id
      and w.user_id::text = (select auth.uid())::text
  );
$$;

create or replace function private.can_manage_team_workspace(target_workspace_id text)
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select exists (
    select 1
    from public.members m
    where m.user_id = (select auth.uid())
      and m.role = 'admin'
      and target_workspace_id = any(coalesce(m.workspace_ids, array[]::text[]))
  ) or exists (
    select 1
    from public.workspaces w
    where w.id = target_workspace_id
      and w.user_id::text = (select auth.uid())::text
  );
$$;

alter table public.teams enable row level security;
alter table public.team_members enable row level security;

do $$
declare policy_row record;
begin
  for policy_row in select policyname from pg_policies where schemaname = 'public' and tablename = 'teams'
  loop execute format('drop policy if exists %I on public.teams', policy_row.policyname); end loop;
  for policy_row in select policyname from pg_policies where schemaname = 'public' and tablename = 'team_members'
  loop execute format('drop policy if exists %I on public.team_members', policy_row.policyname); end loop;
end $$;

create policy teams_select_workspace on public.teams for select to authenticated
using (private.can_view_team_workspace(workspace_id));
create policy teams_insert_admin on public.teams for insert to authenticated
with check (user_id = (select auth.uid()) and private.can_manage_team_workspace(workspace_id));
create policy teams_update_admin on public.teams for update to authenticated
using (private.can_manage_team_workspace(workspace_id))
with check (private.can_manage_team_workspace(workspace_id));
create policy teams_delete_admin on public.teams for delete to authenticated
using (private.can_manage_team_workspace(workspace_id));

create policy team_members_select_workspace on public.team_members for select to authenticated
using (exists (
  select 1 from public.teams t
  where t.id = team_id and private.can_view_team_workspace(t.workspace_id)
));
create policy team_members_insert_admin on public.team_members for insert to authenticated
with check (exists (
  select 1 from public.teams t
  where t.id = team_id and private.can_manage_team_workspace(t.workspace_id)
));
create policy team_members_update_admin on public.team_members for update to authenticated
using (exists (
  select 1 from public.teams t
  where t.id = team_id and private.can_manage_team_workspace(t.workspace_id)
)) with check (exists (
  select 1 from public.teams t
  where t.id = team_id and private.can_manage_team_workspace(t.workspace_id)
));
create policy team_members_delete_admin on public.team_members for delete to authenticated
using (exists (
  select 1 from public.teams t
  where t.id = team_id and private.can_manage_team_workspace(t.workspace_id)
));

grant select, insert, update, delete on table public.teams to authenticated;
grant select, insert, update, delete on table public.team_members to authenticated;
grant usage, select on all sequences in schema public to authenticated;
revoke all on table public.teams from anon;
revoke all on table public.team_members from anon;
